---
title: "SQL learning"
author: "Noah Nyland"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This markdown is only meant to test out and play around with SQL 

```{r}
# need an R chunk to create an r database 
library(odbc)# contains drivers to connect to data base 
library(DBI) # contains functions for interacting with database 
# we need to create a sample database since we dont have real one 
library(RSQLite)# can create in memory database in SQL
library(RSQL) # allows us to process SQL queries 
library(tidyverse)#Provides helpful functions and sample data to use in R 

data("population")
head(population)


data("who")
head(who)

#build the place holder database 
con<- dbConnect(drv = RSQLite::SQLite(),
                dbname = ":memory:")

dbListTables(con)
#character(0)<- nothing loaded yet 

#Load Population and who 
dbWriteTable(conn = con,name = "population",value = population)

dbWriteTable(conn = con,name = "who", value = who)

dbListTables(con)
#[1] "population' , "who"

#Now to Query the Database 

res<- DBI::dbGetQuery(conn = con, statement = "SELECT who.country, who.year, who.new_sp_m014, population.population 
                FROM population, who 
                WHERE who.country = 'Afghanistan' AND 
                who.year > 1995 AND 
                who.country = population.country AND 
                who.year = population.year
                ")
res
# now to use SQL in R 
```
```{sql connection=con, output.var = "M1_results"}
SELECT population.population,who.year,who.country 
FROM who, population WHERE who.country = "France" AND who.year >= 1980 

 
```

now open an R chunk and past the output variables name
```{r}
countryy<-function(string,output){
if (string %in% output){
 print ("country is in Database")}
else{
  print("Country is not in Database")
}
  }
countryy("France",M1_results$country)

```

